// Builds play/achievements_translations.md from the game's own translations (src/i18n): every
// achievement's name and description in the 30 languages, to copy into Play Console
// (Play Games Services > Achievements > an achievement > Manage translations).
//
//   node play/gen-loc.mjs
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const en = (await import(pathToFileURL(join(root, 'src/i18n/en.js')))).default;
const src = readFileSync(join(root, 'src/i18n/index.js'), 'utf8');
const LANGS = [...src.matchAll(/\['([\w-]+)', '([^']+)', '\w+'\]/g)].map(m => [m[1], m[2]]);
const ORDER = ['FIRST_KO', 'FIRST_WIN', 'RAMPAGE', 'POWER_HUNGRY', 'ONLINE_WIN', 'SQUAD_UP', 'WORLD_TOUR', 'JACK_OF_ALL', 'VETERAN', 'CENTURION', 'PODIUM', 'SUPER_KO', 'NIGHT_OWL', 'CRATE_CRUSHER', 'CHAMPION'];

const locales = Object.fromEntries(readdirSync(join(root, 'src/i18n/locales'))
  .map(f => [f.replace('.json', ''), JSON.parse(readFileSync(join(root, 'src/i18n/locales', f), 'utf8'))]));
const cell = s => s.replace(/\|/g, '\|');

let out = '# Play Games achievement translations\n\nGenerated by `node play/gen-loc.mjs` from `src/i18n`: do not edit by hand.\n';
for (const id of ORDER) {
  out += `\n## ${en[`ach.${id}`]} (\`${id}\`)\n\n| Language | Name | Description |\n| --- | --- | --- |\n`;
  for (const [code, label] of LANGS) {
    const d = { ...en, ...(locales[code] || {}) };
    out += `| ${label} (${code}) | ${cell(d[`ach.${id}`])} | ${cell(d[`ach.${id}.desc`])} |\n`;
  }
}
writeFileSync(join(root, 'play/achievements_translations.md'), out);
console.log(`play/achievements_translations.md: ${LANGS.length} languages x ${ORDER.length} achievements`);
