class_name AudioManager
extends Node
# Port of src/audio.js: pooled one-shot SFX (with a simple distance falloff), music playlists with
# crossfade, ducking, low-health low-pass, weather ambience beds and a user mix (master / sfx /
# music / ambience / mute) persisted in user://audio.cfg.
#
# Usage:  var audio := AudioManager.new(); add_child(audio)
#         audio.play("click");  audio.play("hit", world_pos);  audio.play_music("m_grove")
# Every sound is an OGG generated by godot/tools/convert-audio.mjs from public/assets/{sfx,music}.
#
# CPU budget: a sound start is cheap natively but costs milliseconds on the web export (each start
# is a Web Audio sample playback set up from the main thread). Phones and tablets on Low, and the
# web, start at most START_BUDGET sounds a frame (a loud one always gets through), Low phones keep
# LEAN_VOICES voices, and the menu's backdrop match drops its faint sounds sooner there.

const SFX_DIR := "res://assets/audio/sfx/"
const MUSIC_DIR := "res://assets/audio/music/"
const MAX_VOICES := 12
const LEAN_VOICES := 8
const START_BUDGET := 2            # sounds started per frame (web, Low phones; 1 in a Low phone browser)
const COOLDOWN_MS := 35            # per-sound minimum gap, so repeats do not machine-gun
const SETTINGS_PATH := "user://audio.cfg"

# Internal balance between buses (same numbers as the web BASE table).
const BASE := {"master": 0.8, "sfx": 0.55, "music": 0.28, "amb": 0.5}
const GAIN := {"shot": 0.5, "hit": 0.7, "hurt": 0.8, "click": 0.6, "victory": 0.9, "defeat": 0.9, "gas": 0.6,
	"shot_ray": 0.45, "shot_ice": 0.5, "shot_zap": 0.5, "hit_confirm": 0.75, "ko": 0.8, "heartbeat": 0.9,
	"sting_three": 0.7, "sting_duel": 0.75, "sting_finalko": 0.8}
# Friendly names used by the game code -> [file, gain, pitch] (pitch 0 = random jitter).
const ALIASES := {
	"tick": ["click", 1.0, 1.25], "go": ["ready", 1.0, 0.0], "ui": ["click", 1.0, 0.0],
	"damage": ["hurt", 1.0, 0.0], "hit": ["hit_confirm", 1.0, 0.0], "kill": ["ko", 1.0, 0.0],
	"win": ["victory", 1.0, 1.0], "lose": ["defeat", 1.0, 1.0], "low_health": ["heartbeat", 0.8, 1.0],
	"death": ["death", 1.0, 0.0],
}
# Attack sound of each brawler (from combat.js).
const ATTACK := {"blaster": "shotgun", "gunslinger": "shot_ray", "frostbite": "shot_ice", "volt": "shot_zap",
	"bomber": "throw", "kappa": "bubble", "pipchomp": "lunge", "mochi": "bump"}
# combat.js: what a super sounds like besides "super" + the brawler's bark.
const SUPER_EXTRA := {"blaster": "shotgun", "bomber": "throw", "pipchomp": "trap_plant", "mochi": "pound_leap", "kappa": "wave"}
const JINGLES := ["fanfare", "victory", "defeat"]
const PLAYLISTS := {"menu": ["menu"], "lobby": ["lobby", "menu"], "battle": ["battle", "battle2"], "final": ["final"]}
const BEDS := {"rain": "amb_rain", "sandstorm": "amb_storm", "snow": "amb_snow", "fog": "amb_marsh"}

# User mix, 0..1 (setters apply immediately and persist).
var master := 0.5: set = _set_master
var sfx := 1.0: set = _set_sfx
var music := 0.8: set = _set_music
var amb := 0.8: set = _set_amb
var muted := false: set = _set_muted
var track := "auto"                # "auto" follows the game, "off", or a fixed playlist name
var listener := Vector3.ZERO       # the local player's position (distances are measured from it)
var attract := false               # the menu's backdrop match (menu_showcase.gd): its sounds are quieter (game.js volumeAt)

static var current: AudioManager   # the game's (fighters and effects play through it)

var _voices: Array[AudioStreamPlayer] = []
var _voice_t: Array[int] = []      # start time (ms) of each voice, to steal the oldest
var _last: Dictionary = {}         # sound -> last start (ms)
var _cache: Dictionary = {}        # name -> AudioStream or null (missing)
var _suspended := false
var _paused_voices: Array = []
var _jingle: AudioStreamPlayer

var _mus: Array[AudioStreamPlayer] = []
var _mus_fade: Array[float] = [0.0, 0.0]
var _mus_target: Array[float] = [0.0, 0.0]
var _mus_cur := 0
var _song := ""
var _playlist: Array = []
var _song_idx := 0
var _want := ""
var _duck := 1.0
var _duck_hold := 0.0
var _danger := 0.0
var _danger_now := 0.0
var _lp: AudioEffectLowPassFilter
var _amb: Dictionary = {}          # name -> {p, fade, target}
var _weather_bed := ""
var _night := 0.0
var _bus_sfx := -1
var _bus_music := -1
var _bus_amb := -1
var _starts := 0                   # sounds started this frame
var _lean := false                 # a phone / tablet on Low (refreshed each frame)
var _budget := false               # the start budget applies (web or _lean)
var _vol_set: Array[float] = [INF, INF]   # the music players' last volume_db (set only on a change)

func _ready() -> void:
	current = self
	process_mode = Node.PROCESS_MODE_ALWAYS
	_bus_sfx = _make_bus("SFX")
	_bus_music = _make_bus("Music")
	_bus_amb = _make_bus("Amb")
	_lp = AudioEffectLowPassFilter.new()
	_lp.cutoff_hz = 20000.0
	for i in MAX_VOICES:
		var p := AudioStreamPlayer.new()
		p.bus = "SFX"
		p.process_mode = Node.PROCESS_MODE_ALWAYS
		add_child(p)
		_voices.append(p)
		_voice_t.append(0)
	_jingle = AudioStreamPlayer.new()
	_jingle.bus = "SFX"
	add_child(_jingle)
	for i in 2:
		var m := AudioStreamPlayer.new()
		m.bus = "Music"
		m.volume_db = -80.0
		m.finished.connect(_on_song_end.bind(i))
		add_child(m)
		_mus.append(m)
	_load_settings()
	_apply_mix()

func _make_bus(bus_name: String) -> int:
	var i := AudioServer.get_bus_index(bus_name)
	if i == -1:
		AudioServer.add_bus()
		i = AudioServer.bus_count - 1
		AudioServer.set_bus_name(i, bus_name)
		AudioServer.set_bus_send(i, "Master")
	return i

# ------------------------------------------------------------------ mix

func _apply_mix() -> void:
	if _bus_sfx < 0:
		return
	AudioServer.set_bus_mute(0, muted)
	AudioServer.set_bus_volume_db(0, _db(BASE.master * master))
	AudioServer.set_bus_volume_db(_bus_sfx, _db(BASE.sfx * sfx))
	AudioServer.set_bus_volume_db(_bus_music, _db(BASE.music * music))
	AudioServer.set_bus_volume_db(_bus_amb, _db(BASE.amb * amb))

func _db(lin: float) -> float:
	return linear_to_db(maxf(lin, 0.0001))

func _set_master(v: float) -> void:
	master = clampf(v, 0.0, 1.0); _apply_mix(); _save_settings()
func _set_sfx(v: float) -> void:
	sfx = clampf(v, 0.0, 1.0); _apply_mix(); _save_settings()
func _set_music(v: float) -> void:
	music = clampf(v, 0.0, 1.0); _apply_mix(); _save_settings()
func _set_amb(v: float) -> void:
	amb = clampf(v, 0.0, 1.0); _apply_mix(); _save_settings()
func _set_muted(v: bool) -> void:
	muted = v; _apply_mix(); _save_settings()

func toggle_mute() -> bool:
	muted = not muted
	return muted

# "auto" | "off" | "menu" | "battle" ...: re-evaluates what is playing.
func set_track(t: String) -> void:
	track = t
	_save_settings()
	play_music(_want)

func _load_settings() -> void:
	var cf := ConfigFile.new()
	if cf.load(SETTINGS_PATH) != OK:
		return
	master = float(cf.get_value("audio", "master", master))
	sfx = float(cf.get_value("audio", "sfx", sfx))
	music = float(cf.get_value("audio", "music", music))
	amb = float(cf.get_value("audio", "amb", amb))
	muted = bool(cf.get_value("audio", "muted", muted))
	track = String(cf.get_value("audio", "track", track))

func _save_settings() -> void:
	if not is_inside_tree():
		return
	var cf := ConfigFile.new()
	for k in ["master", "sfx", "music", "amb", "muted", "track"]:
		cf.set_value("audio", k, get(k))
	cf.save(SETTINGS_PATH)

# ------------------------------------------------------------------ streams

func _stream(base: String, path_dir: String = "") -> AudioStream:
	var key := path_dir + base
	if _cache.has(key):
		return _cache[key]
	var s: AudioStream = null
	var t0 := PerfProbe.now()
	for dir in ([path_dir] if path_dir != "" else [SFX_DIR, MUSIC_DIR]):
		var path: String = dir + base + ".ogg"
		if ResourceLoader.exists(path):
			s = load(path) as AudioStream
			break
	PerfProbe.add("audio.load", t0)
	_cache[key] = s
	return s

func has_sound(n: String) -> bool:
	return _stream(n) != null

# ------------------------------------------------------------------ one-shots

# name: a file in assets/audio/sfx ("hit_confirm"), an alias ("damage", "kill", "win", "tick"...),
# "atk_<brawler>" / "super_<brawler>", or "m_<map>" (starts that map's music).
# world_pos: Vector3 in world units for a distance falloff from `listener`; null = full volume.
func play(sound: String, world_pos: Variant = null, vol: float = 1.0, rate: float = 0.0) -> void:
	if _suspended or muted:
		return
	if sound.begins_with("m_"):
		play_music(sound)
		return
	var gain := vol
	var file := sound
	var pitch := rate
	if sound.begins_with("atk_") or sound.begins_with("super_"):
		var key := sound.get_slice("_", 1)
		var sup := sound.begins_with("super_")
		if sup:
			play("super", world_pos, vol)
			if SUPER_EXTRA.has(key):
				play(SUPER_EXTRA[key], world_pos, vol)
			file = "bark_%s_super" % key
			gain *= 0.9
		else:
			file = ATTACK.get(key, "shot")
	elif ALIASES.has(sound):
		var a: Array = ALIASES[sound]
		file = a[0]
		gain *= float(a[1])
		if pitch == 0.0:
			pitch = float(a[2])
	if world_pos is Vector3:
		var d := Vector3(world_pos) - listener
		gain *= 1.0 / (1.0 + (d.x * d.x + d.z * d.z) / 150.0)
	if attract and world_pos is Vector3:   # only the world's sounds: the menu's clicks stay as loud
		gain *= 0.35
		if _lean and gain < 0.08:
			return
	if gain < 0.03:
		return
	if _budget and _starts >= (1 if _lean and OS.has_feature("web") else START_BUDGET) and gain < 0.5:
		return
	var stream := _stream(file)
	if stream == null:
		return
	var now := Time.get_ticks_msec()
	if _last.has(file) and now - int(_last[file]) < COOLDOWN_MS:
		return
	_last[file] = now
	gain *= float(GAIN.get(file, 1.0))
	var jingle := JINGLES.has(file)
	if jingle:
		file = "fanfare" if file == "victory" and _stream("fanfare") != null else file
		stream = _stream(file)
		stop_music(0.6)
		_jingle.stream = stream
		_jingle.volume_db = _db(gain)
		_jingle.pitch_scale = 1.0
		_jingle.play()
		return
	var p := _free_voice(now, gain)
	if p == null:
		return
	_starts += 1
	var t0 := PerfProbe.now()
	p.stream = stream
	p.volume_db = _db(gain)
	p.pitch_scale = pitch if pitch > 0.0 else randf_range(0.94, 1.06)
	p.play()
	PerfProbe.add("audio.play", t0)

func _free_voice(now: int, gain: float) -> AudioStreamPlayer:
	var oldest := 0
	for i in (LEAN_VOICES if _lean else _voices.size()):
		if not _voices[i].playing:
			_voice_t[i] = now
			return _voices[i]
		if _voice_t[i] < _voice_t[oldest]:
			oldest = i
	if gain < 0.25:
		return null            # a faint sound never steals a voice
	_voice_t[oldest] = now
	return _voices[oldest]

func stop_jingle(fade: float = 0.3) -> void:
	if _jingle.playing:
		var tw := create_tween()
		tw.tween_property(_jingle, "volume_db", -60.0, fade)
		tw.tween_callback(_jingle.stop)

# ------------------------------------------------------------------ music

# name: "menu", "lobby", "battle", "final", "m_<mapKey>" (that map's theme first, then the battle
# songs, plus the map's weather ambience) or "" / null to stop.
func play_music(name: Variant) -> void:
	var n := "" if name == null else String(name)
	_want = n
	if n != "":
		stop_jingle()
	var t := track
	var want := n if t == "auto" else ("" if t == "off" else t)
	var list: Array = []
	if want.begins_with("m_"):
		list = [want, "battle", "battle2"]
		_set_weather_from_map(want.substr(2))
	elif want != "":
		list = PLAYLISTS.get(want, [want])
		_weather_bed = ""
		_update_ambience()
	else:
		_weather_bed = ""
		_update_ambience(true)
	list = list.filter(func(s): return _stream(s, MUSIC_DIR) != null)
	if list == _playlist:
		if _song != "" and not _mus[_mus_cur].playing and not _suspended:
			_mus[_mus_cur].play()
		return
	_playlist = list
	_song_idx = 0
	_switch_song(list[0] if not list.is_empty() else "")

func stop_music(fade: float = 0.6) -> void:
	_playlist = []
	_want = ""
	_switch_song("", fade)
	_weather_bed = ""
	_update_ambience(true)

func _switch_song(name: String, _fade: float = 0.4) -> void:
	if name == _song and name != "":
		return
	_mus_target[_mus_cur] = 0.0
	_song = name
	if name == "":
		return
	_mus_cur = 1 - _mus_cur
	var p := _mus[_mus_cur]
	p.stream = _stream(name, MUSIC_DIR)
	_mus_fade[_mus_cur] = 0.0
	_mus_target[_mus_cur] = 1.0
	p.volume_db = -80.0
	_vol_set[_mus_cur] = -80.0
	if not _suspended:
		p.play()

func _on_song_end(i: int) -> void:
	if i != _mus_cur or _playlist.is_empty() or _suspended:
		return
	_song_idx = (_song_idx + 1) % _playlist.size()
	var nxt: String = _playlist[_song_idx]
	if nxt == _song:
		_mus[i].play()
	else:
		_switch_song(nxt)

# Music dips by 6 dB for a moment (your super, your KOs), back over `sec`.
func duck(sec: float = 0.6) -> void:
	_duck = 0.5
	_duck_hold = 0.15 + sec

# Low health (0..1): the music closes down to a 1200 Hz low-pass.
func set_danger(v: float) -> void:
	_danger = clampf(v, 0.0, 1.0)

# ------------------------------------------------------------------ ambience

func _set_weather_from_map(map_key: String) -> void:
	var m: Dictionary = GameData.maps.get(map_key, {})
	_weather_bed = BEDS.get(String(m.get("weather", "clear")), "")
	_update_ambience()

# night: 0 = day birds and wind, 1 = crickets.
func set_night(v: float) -> void:
	_night = clampf(v, 0.0, 1.0)
	_update_ambience()

func _update_ambience(off: bool = false) -> void:
	var under := 0.35 if _weather_bed != "" else 1.0
	var levels := {"amb_day": 0.0 if off else (1.0 - _night) * 1.6 * under,
		"amb_night": 0.0 if off else _night * 3.2 * under}
	for b in BEDS.values():
		levels[b] = 1.4 if (b == _weather_bed and not off) else 0.0
	for n in levels:
		if levels[n] > 0.0 and not _amb.has(n):
			var s := _stream(n, MUSIC_DIR)
			if s == null:
				continue
			var st := s.duplicate() as AudioStreamOggVorbis
			st.loop = true
			var p := AudioStreamPlayer.new()
			p.bus = "Amb"
			p.stream = st
			p.volume_db = -80.0
			add_child(p)
			if not _suspended:
				p.play()
			_amb[n] = {"p": p, "fade": 0.0, "target": 0.0}
		if _amb.has(n):
			_amb[n].target = levels[n]

# ------------------------------------------------------------------ frame + lifecycle

func _process(delta: float) -> void:   # timed for the perf overlay (perf_probe.gd)
	var t0 := PerfProbe.now()
	_process_timed(delta)
	PerfProbe.add("audio", t0)

func _process_timed(delta: float) -> void:
	_starts = 0
	_lean = Quality.mobile() and Quality.name_now() == "low"
	_budget = _lean or OS.has_feature("web")
	if _suspended:
		return
	# music crossfade + duck
	if _duck_hold > 0.0:
		_duck_hold -= delta
	else:
		_duck = minf(1.0, _duck + delta * 1.5)
	for i in 2:
		_mus_fade[i] = move_toward(_mus_fade[i], _mus_target[i], delta / 0.9)
		var p := _mus[i]
		var db := _db(_mus_fade[i] * _duck)
		if absf(db - _vol_set[i]) > 0.01:
			_vol_set[i] = db
			p.volume_db = db
		if _mus_target[i] == 0.0 and _mus_fade[i] <= 0.0 and p.playing:
			p.stop()
	# low-pass for danger, only present on the bus while it matters
	_danger_now = lerpf(_danger_now, _danger, minf(delta * 4.0, 1.0))
	var has_fx := AudioServer.get_bus_effect_count(_bus_music) > 0
	if _danger_now > 0.01:
		if not has_fx:
			AudioServer.add_bus_effect(_bus_music, _lp)
		_lp.cutoff_hz = 20000.0 * pow(1200.0 / 20000.0, _danger_now)
	elif has_fx:
		AudioServer.remove_bus_effect(_bus_music, 0)
	if _amb.is_empty():
		return
	for n in _amb.keys():
		var a: Dictionary = _amb[n]
		if a.fade == a.target and a.target > 0.0:
			continue   # steady: nothing to set
		a.fade = move_toward(a.fade, a.target, delta / 1.2)
		a.p.volume_db = _db(a.fade)
		if a.target == 0.0 and a.fade <= 0.0 and a.p.playing:
			a.p.stop()
			a.p.queue_free()
			_amb.erase(n)

func _notification(what: int) -> void:
	# battery: nothing plays while the app is in the background
	match what:
		NOTIFICATION_APPLICATION_FOCUS_OUT, NOTIFICATION_APPLICATION_PAUSED:
			_suspend(true)
		NOTIFICATION_APPLICATION_FOCUS_IN, NOTIFICATION_APPLICATION_RESUMED:
			_suspend(false)

func _suspend(on: bool) -> void:
	if on == _suspended:
		return
	_suspended = on
	var all: Array = _voices + _mus + [_jingle]
	for a in _amb.values():
		all.append(a.p)
	if on:
		_paused_voices = all.filter(func(p): return p.playing)
		for p in _paused_voices:
			p.stream_paused = true
	else:
		for p in _paused_voices:
			if is_instance_valid(p):
				p.stream_paused = false
		_paused_voices = []
